service: game-session

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  sessionTableName: 'session-table-${self:provider.stage}'
  gameTableName: 'game-table-${self:provider.stage}'
  wsgi:
    app: game_sessions.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["SessionTable", "Arn" ] }
        - { "Fn::GetAtt": ["GameTable", "Arn" ] }
  environment:
    SESSION_TABLE_NAME: ${self:custom.sessionTableName}
    GAME_TABLE_NAME: ${self:custom.gameTableName}

package:
  individually: true

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    SessionTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: session_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: session_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.sessionTableName}
    GameTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: session_id
            AttributeType: S
          -
            AttributeName: game_id
            AttributeType: S
        KeySchema:
          -
            AttributeName: session_id
            KeyType: HASH
          -
            AttributeName: game_id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.gameTableName}
